{
 "title": "GWW Addon [test]",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Graffiti Wall Writer Addon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Pixels",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gww_pixels_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Todo Pixels",
   "type": "piechart",
   "description": "Pixels that still need to be painted.",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gww_pixels_todo", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Pixels left to draw",
   "type": "timeseries",
   "description": "Pixels that still need to be drawn.\nFix are pixels that are the wrong color and need redrawing.",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    {
     "expr": "gww_pixels_todo{type=~\"Fix|Normal\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fetch Latency",
   "type": "histogram",
   "gridPos": { "h": 15, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status, url) (rate(gww_http_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{url}} ({{status}})"
    }
   ]
  },
  {
   "title": "Pixels left to draw",
   "type": "stat",
   "description": "Pixels that still need to be drawn.\nFix are pixels that are the wrong color and need redrawing.",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gww_pixels_todo{type=~\"Fix|Normal\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pixels per 24h",
   "type": "stat",
   "description": "Amount of pixels drawn in the last 7200 blocks (24 hours).\nRPL is the section that our drawer is focused on.\nGlobal is the entire canvas.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gww_pixels_speed", "legendFormat": "{{section}}" }
   ]
  },
  {
   "title": "Pixels per day",
   "type": "timeseries",
   "description": "Pixels draw speed in the last 24h",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 16 },
   "targets": [
    { "expr": "gww_pixels_speed", "legendFormat": "{{section}}" }
   ]
  },
  {
   "title": "My Pixels",
   "type": "timeseries",
   "description": "Pixels drawn by my validators (as supplied to the drawer)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pixel" } },
   "targets": [
    { "expr": "gww_pixels_mine", "legendFormat": "{{validator}}" }
   ]
  },
  {
   "title": "TEST123",
   "type": "text",
   "gridPos": { "h": 23, "w": 11, "x": 8, "y": 23 },
   "options": {
    "content": "<div style=\"max-width: 1000px; margin:0 auto;\">\n  <a href=\"https://beacon.gnosischain.com/graffitiwall\" style=\"display: block;\" target=\"_blank\" title=\"Open in new tab\">\n    <img src=/public/addons/rocketpool/wall.png title=\"beaconcha.in/graffitiwall\">\n  </a>\n</div>"
   }
  },
  {
   "title": "TEST123",
   "type": "text",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 29 },
   "options": {
    "content": "<div style=\"max-width: 1000px; margin:0 auto;\">\n  <a href=/public/addons/rocketpool/drawnSection.png style=\"display: block;\" target=\"_blank\" title=\"Open in new tab\">\n    <img src=\"/public/addons/rocketpool/drawnSection.png\">\n  </a>\n</div>"
   }
  }
 ]
}